CONTIKI_PROJECT = udp-server udp-client-pressure udp-client-rain udp-client-temp udp-client-video udp-client-wind
all: $(CONTIKI_PROJECT)

# MAKE_MAC = MAKE_MAC_TSCH

CONTIKI=../../contiki-ng
include $(CONTIKI)/Makefile.include
